name: SLZB-07Mg24 Firmware Eraser
device: EFR32MG24A020F1024IM40
base_project: src/firmware_eraser
filename: "{manifest_name}_{sdk_version}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: firmware_eraser
