name: ZB-GW04-1v2 Zigbee
device: EFR32MG21A020F768IM32
base_project: src/ncp-uart-hw_EFR32MG21A020F768IM32
filename: "{manifest_name}_{ezsp_version}"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

c_defines:
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_TX_PIN:  1

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RX_PIN:  0

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  3

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  4

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 32

  SL_CLOCK_MANAGER_HFXO_FREQ: 38400000
  SL_CLOCK_MANAGER_HFXO_CTUNE: 128
  SL_CLOCK_MANAGER_HFXO_PRECISION: 50
  SL_CLOCK_MANAGER_LFXO_CTUNE: 63
  SL_CLOCK_MANAGER_LFXO_PRECISION: 50

  SL_RAIL_UTIL_RSSI_OFFSET: -11

  SL_ZIGBEE_ADDRESS_TABLE_SIZE: 16
  SL_ZIGBEE_MULTICAST_TABLE_SIZE: 16
  SL_ZIGBEE_ROUTE_TABLE_SIZE: 16
  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 20
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 15
  SL_ZIGBEE_NEIGHBOR_TABLE_SIZE: 16
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 150
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 32
