name: ZBDongle-E Zigbee
device: EFR32MG21A020F768IM32
base_project: src/rcp-uart-802154-blehci_EFR32MG21A020F768IM32
filename: "{manifest_name}_{sdk_version}"

gbl:
  fw_type: rcp-uart-802154-blehci-sw
  dynamic: ["ezsp_version", "ot_version", "ble_version", "cpc_version"]
  baudrate: 460800

c_defines:
  SL_CPC_DRV_UART_VCOM_BAUDRATE: 460800
  SL_CPC_DRV_UART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlNone

  SL_CPC_DRV_UART_VCOM_PERIPHERAL: USART0
  SL_CPC_DRV_UART_VCOM_PERIPHERAL_NO: 0

  SL_CPC_DRV_UART_VCOM_TX_PORT: gpioPortB
  SL_CPC_DRV_UART_VCOM_TX_PIN: 1

  SL_CPC_DRV_UART_VCOM_RX_PORT: gpioPortB
  SL_CPC_DRV_UART_VCOM_RX_PIN: 0

  SL_CPC_DRV_UART_VCOM_CTS_PORT: 0
  SL_CPC_DRV_UART_VCOM_CTS_PIN: 0

  SL_CPC_DRV_UART_VCOM_RTS_PORT: 0
  SL_CPC_DRV_UART_VCOM_RTS_PIN: 0

  SL_CPC_DRV_UART_VCOM_RX_QUEUE_SIZE: 10
  SL_CPC_DRV_UART_VCOM_TX_QUEUE_SIZE: 10

  SL_CPC_TX_QUEUE_ITEM_MAX_COUNT: 15
  SL_CPC_RX_BUFFER_MAX_COUNT: 15

  SL_CLOCK_MANAGER_HFXO_FREQ: 38400000
  SL_CLOCK_MANAGER_HFXO_CTUNE: 128
  SL_CLOCK_MANAGER_HFXO_PRECISION: 50
  SL_CLOCK_MANAGER_LFXO_CTUNE: 63
  SL_CLOCK_MANAGER_LFXO_PRECISION: 50

  SL_RAIL_UTIL_RSSI_OFFSET: -11
