name: TubesZB MGM24 HW Max Zigbee
device: MGM240PA32VNN
base_project: src/ncp-uart-hw_MGM240PA32VNN
filename: "{manifest_name}_{ezsp_version}"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

c_defines:
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  7

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  8

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 128

  SL_CLOCK_MANAGER_HFXO_FREQ: 39000000
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_HFXO_PRECISION: 50
  SL_CLOCK_MANAGER_LFXO_CTUNE: 63
  SL_CLOCK_MANAGER_LFXO_PRECISION: 50

  SL_RAIL_UTIL_RSSI_OFFSET: 0

  SL_ZIGBEE_ADDRESS_TABLE_SIZE: 250
  SL_ZIGBEE_MULTICAST_TABLE_SIZE: 26
  SL_ZIGBEE_ROUTE_TABLE_SIZE: 254
  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 255
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 30
  SL_ZIGBEE_NEIGHBOR_TABLE_SIZE: 26
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 254
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 64
  SL_ZIGBEE_APS_DUPLICATE_REJECTION_MAX_ENTRIES: 255
